# Use the official MongoDB image from Docker Hub
FROM mongo:latest

# Expose the MongoDB port
EXPOSE 27017

# Default command to run MongoDB with authentication
CMD ["mongod", "--auth", "--bind_ip_all"]
